name: Lint, Build & Publish
run-name: Lint, Build & Publish

on:
  workflow_call:

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Checks out the repository code.
        uses: actions/checkout@v4

      - name: Set up Python
        # Installs Python 3.13 and sets it as the default python3.
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install python3.13 python3.13-venv -y
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1
          sudo update-alternatives --set python3 /usr/bin/python3.13

      - name: Install dependencies
        # Creates a virtual environment and installs development dependencies.
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Run Linter
        # Activates the environment and runs lint checks via hatch.
        run: |
          source venv/bin/activate
          hatch run lint

  build:
    needs: lint
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      # Exposes the TARGET_TAG output from the 'vars' step.
      target_tag: ${{ steps.vars.outputs.TARGET_TAG }}
    steps:
      - name: Checkout repository
        # Checks out the code again (for this separate job).
        uses: actions/checkout@v4

      - name: Set up Python
        # Installs Python 3.13 and sets it as the default python3.
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install python3.13 python3.13-venv -y
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1
          sudo update-alternatives --set python3 /usr/bin/python3.13

      - name: Install dependencies
        # Creates a virtual environment and installs development dependencies.
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build Project
        # Builds project
        run: |
          source venv/bin/activate
          python3 -m build

  test:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        # Installs Python 3.13 and sets it as the default python3.
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install python3.13 python3.13-venv -y
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1
          sudo update-alternatives --set python3 /usr/bin/python3.13

      - name: Install dependencies
        # Creates a virtual environment and installs dev/runtime deps + hatch.
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          hatch run test


